---
-
  hosts: all
  
  pre_tasks:
    - include: roles/rabbit/tasks/setup.yml
  
  vars:
    ssm:
      params:
        - name: rb_admin_password
          key: "rabbit-admin-pw"
    rb:
      port: 5671
      management_port: 15671
      plugins:
        - rabbitmq_aws
        - rabbitmq_management
        - rabbitmq_management_agent
        - rabbitmq_peer_discovery_aws
        - rabbitmq_shovel
        - rabbitmq_shovel_management
        - rabbitmq_autocluster
      ulimit: 65536
      users:
        - name: admin
          password: "{{ rb_admin_password }}"
          tags: administrator,management
          permissions:
            - vhost: /
              configure_priv: .*
              read_priv: .*
              write_priv: .*
  
  roles:
    - { role: rabbit }
